//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceAPI
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceAPI.WebServiceAPISoap")]
    public interface WebServiceAPISoap
    {
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 strCRVName 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setCRVPrint", ReplyAction="*")]
        WebServiceAPI.setCRVPrintResponse setCRVPrint(WebServiceAPI.setCRVPrintRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setCRVPrint", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceAPI.setCRVPrintResponse> setCRVPrintAsync(WebServiceAPI.setCRVPrintRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 strCRVName 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setCRVToPDF", ReplyAction="*")]
        WebServiceAPI.setCRVToPDFResponse setCRVToPDF(WebServiceAPI.setCRVToPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setCRVToPDF", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceAPI.setCRVToPDFResponse> setCRVToPDFAsync(WebServiceAPI.setCRVToPDFRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 strCRVName 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setCRVToIMG", ReplyAction="*")]
        WebServiceAPI.setCRVToIMGResponse setCRVToIMG(WebServiceAPI.setCRVToIMGRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setCRVToIMG", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceAPI.setCRVToIMGResponse> setCRVToIMGAsync(WebServiceAPI.setCRVToIMGRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCRVPrintRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCRVPrint", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceAPI.setCRVPrintRequestBody Body;
        
        public setCRVPrintRequest()
        {
        }
        
        public setCRVPrintRequest(WebServiceAPI.setCRVPrintRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setCRVPrintRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCRVName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strScrpit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strPrinterName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sqlUserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sqlPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sqlCatalog;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sqlSource;
        
        public setCRVPrintRequestBody()
        {
        }
        
        public setCRVPrintRequestBody(string strCRVName, string strScrpit, string strPrinterName, string sqlUserID, string sqlPassword, string sqlCatalog, string sqlSource)
        {
            this.strCRVName = strCRVName;
            this.strScrpit = strScrpit;
            this.strPrinterName = strPrinterName;
            this.sqlUserID = sqlUserID;
            this.sqlPassword = sqlPassword;
            this.sqlCatalog = sqlCatalog;
            this.sqlSource = sqlSource;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCRVPrintResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCRVPrintResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceAPI.setCRVPrintResponseBody Body;
        
        public setCRVPrintResponse()
        {
        }
        
        public setCRVPrintResponse(WebServiceAPI.setCRVPrintResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setCRVPrintResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setCRVPrintResult;
        
        public setCRVPrintResponseBody()
        {
        }
        
        public setCRVPrintResponseBody(string setCRVPrintResult)
        {
            this.setCRVPrintResult = setCRVPrintResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCRVToPDFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCRVToPDF", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceAPI.setCRVToPDFRequestBody Body;
        
        public setCRVToPDFRequest()
        {
        }
        
        public setCRVToPDFRequest(WebServiceAPI.setCRVToPDFRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setCRVToPDFRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCRVName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strScrpit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strDiskFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sqlUserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sqlPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sqlCatalog;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sqlSource;
        
        public setCRVToPDFRequestBody()
        {
        }
        
        public setCRVToPDFRequestBody(string strCRVName, string strScrpit, string strDiskFileName, string sqlUserID, string sqlPassword, string sqlCatalog, string sqlSource)
        {
            this.strCRVName = strCRVName;
            this.strScrpit = strScrpit;
            this.strDiskFileName = strDiskFileName;
            this.sqlUserID = sqlUserID;
            this.sqlPassword = sqlPassword;
            this.sqlCatalog = sqlCatalog;
            this.sqlSource = sqlSource;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCRVToPDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCRVToPDFResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceAPI.setCRVToPDFResponseBody Body;
        
        public setCRVToPDFResponse()
        {
        }
        
        public setCRVToPDFResponse(WebServiceAPI.setCRVToPDFResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setCRVToPDFResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setCRVToPDFResult;
        
        public setCRVToPDFResponseBody()
        {
        }
        
        public setCRVToPDFResponseBody(string setCRVToPDFResult)
        {
            this.setCRVToPDFResult = setCRVToPDFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCRVToIMGRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCRVToIMG", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceAPI.setCRVToIMGRequestBody Body;
        
        public setCRVToIMGRequest()
        {
        }
        
        public setCRVToIMGRequest(WebServiceAPI.setCRVToIMGRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setCRVToIMGRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCRVName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strScrpit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strPdfFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strImgFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sqlUserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sqlPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sqlCatalog;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string sqlSource;
        
        public setCRVToIMGRequestBody()
        {
        }
        
        public setCRVToIMGRequestBody(string strCRVName, string strScrpit, string strPdfFileName, string strImgFileName, string sqlUserID, string sqlPassword, string sqlCatalog, string sqlSource)
        {
            this.strCRVName = strCRVName;
            this.strScrpit = strScrpit;
            this.strPdfFileName = strPdfFileName;
            this.strImgFileName = strImgFileName;
            this.sqlUserID = sqlUserID;
            this.sqlPassword = sqlPassword;
            this.sqlCatalog = sqlCatalog;
            this.sqlSource = sqlSource;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCRVToIMGResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCRVToIMGResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceAPI.setCRVToIMGResponseBody Body;
        
        public setCRVToIMGResponse()
        {
        }
        
        public setCRVToIMGResponse(WebServiceAPI.setCRVToIMGResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setCRVToIMGResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setCRVToIMGResult;
        
        public setCRVToIMGResponseBody()
        {
        }
        
        public setCRVToIMGResponseBody(string setCRVToIMGResult)
        {
            this.setCRVToIMGResult = setCRVToIMGResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WebServiceAPISoapChannel : WebServiceAPI.WebServiceAPISoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WebServiceAPISoapClient : System.ServiceModel.ClientBase<WebServiceAPI.WebServiceAPISoap>, WebServiceAPI.WebServiceAPISoap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServiceAPISoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceAPISoapClient.GetBindingForEndpoint(endpointConfiguration), WebServiceAPISoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceAPISoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceAPISoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceAPISoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceAPISoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceAPI.setCRVPrintResponse WebServiceAPI.WebServiceAPISoap.setCRVPrint(WebServiceAPI.setCRVPrintRequest request)
        {
            return base.Channel.setCRVPrint(request);
        }
        
        public string setCRVPrint(string strCRVName, string strScrpit, string strPrinterName, string sqlUserID, string sqlPassword, string sqlCatalog, string sqlSource)
        {
            WebServiceAPI.setCRVPrintRequest inValue = new WebServiceAPI.setCRVPrintRequest();
            inValue.Body = new WebServiceAPI.setCRVPrintRequestBody();
            inValue.Body.strCRVName = strCRVName;
            inValue.Body.strScrpit = strScrpit;
            inValue.Body.strPrinterName = strPrinterName;
            inValue.Body.sqlUserID = sqlUserID;
            inValue.Body.sqlPassword = sqlPassword;
            inValue.Body.sqlCatalog = sqlCatalog;
            inValue.Body.sqlSource = sqlSource;
            WebServiceAPI.setCRVPrintResponse retVal = ((WebServiceAPI.WebServiceAPISoap)(this)).setCRVPrint(inValue);
            return retVal.Body.setCRVPrintResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceAPI.setCRVPrintResponse> WebServiceAPI.WebServiceAPISoap.setCRVPrintAsync(WebServiceAPI.setCRVPrintRequest request)
        {
            return base.Channel.setCRVPrintAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceAPI.setCRVPrintResponse> setCRVPrintAsync(string strCRVName, string strScrpit, string strPrinterName, string sqlUserID, string sqlPassword, string sqlCatalog, string sqlSource)
        {
            WebServiceAPI.setCRVPrintRequest inValue = new WebServiceAPI.setCRVPrintRequest();
            inValue.Body = new WebServiceAPI.setCRVPrintRequestBody();
            inValue.Body.strCRVName = strCRVName;
            inValue.Body.strScrpit = strScrpit;
            inValue.Body.strPrinterName = strPrinterName;
            inValue.Body.sqlUserID = sqlUserID;
            inValue.Body.sqlPassword = sqlPassword;
            inValue.Body.sqlCatalog = sqlCatalog;
            inValue.Body.sqlSource = sqlSource;
            return ((WebServiceAPI.WebServiceAPISoap)(this)).setCRVPrintAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceAPI.setCRVToPDFResponse WebServiceAPI.WebServiceAPISoap.setCRVToPDF(WebServiceAPI.setCRVToPDFRequest request)
        {
            return base.Channel.setCRVToPDF(request);
        }
        
        public string setCRVToPDF(string strCRVName, string strScrpit, string strDiskFileName, string sqlUserID, string sqlPassword, string sqlCatalog, string sqlSource)
        {
            WebServiceAPI.setCRVToPDFRequest inValue = new WebServiceAPI.setCRVToPDFRequest();
            inValue.Body = new WebServiceAPI.setCRVToPDFRequestBody();
            inValue.Body.strCRVName = strCRVName;
            inValue.Body.strScrpit = strScrpit;
            inValue.Body.strDiskFileName = strDiskFileName;
            inValue.Body.sqlUserID = sqlUserID;
            inValue.Body.sqlPassword = sqlPassword;
            inValue.Body.sqlCatalog = sqlCatalog;
            inValue.Body.sqlSource = sqlSource;
            WebServiceAPI.setCRVToPDFResponse retVal = ((WebServiceAPI.WebServiceAPISoap)(this)).setCRVToPDF(inValue);
            return retVal.Body.setCRVToPDFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceAPI.setCRVToPDFResponse> WebServiceAPI.WebServiceAPISoap.setCRVToPDFAsync(WebServiceAPI.setCRVToPDFRequest request)
        {
            return base.Channel.setCRVToPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceAPI.setCRVToPDFResponse> setCRVToPDFAsync(string strCRVName, string strScrpit, string strDiskFileName, string sqlUserID, string sqlPassword, string sqlCatalog, string sqlSource)
        {
            WebServiceAPI.setCRVToPDFRequest inValue = new WebServiceAPI.setCRVToPDFRequest();
            inValue.Body = new WebServiceAPI.setCRVToPDFRequestBody();
            inValue.Body.strCRVName = strCRVName;
            inValue.Body.strScrpit = strScrpit;
            inValue.Body.strDiskFileName = strDiskFileName;
            inValue.Body.sqlUserID = sqlUserID;
            inValue.Body.sqlPassword = sqlPassword;
            inValue.Body.sqlCatalog = sqlCatalog;
            inValue.Body.sqlSource = sqlSource;
            return ((WebServiceAPI.WebServiceAPISoap)(this)).setCRVToPDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceAPI.setCRVToIMGResponse WebServiceAPI.WebServiceAPISoap.setCRVToIMG(WebServiceAPI.setCRVToIMGRequest request)
        {
            return base.Channel.setCRVToIMG(request);
        }
        
        public string setCRVToIMG(string strCRVName, string strScrpit, string strPdfFileName, string strImgFileName, string sqlUserID, string sqlPassword, string sqlCatalog, string sqlSource)
        {
            WebServiceAPI.setCRVToIMGRequest inValue = new WebServiceAPI.setCRVToIMGRequest();
            inValue.Body = new WebServiceAPI.setCRVToIMGRequestBody();
            inValue.Body.strCRVName = strCRVName;
            inValue.Body.strScrpit = strScrpit;
            inValue.Body.strPdfFileName = strPdfFileName;
            inValue.Body.strImgFileName = strImgFileName;
            inValue.Body.sqlUserID = sqlUserID;
            inValue.Body.sqlPassword = sqlPassword;
            inValue.Body.sqlCatalog = sqlCatalog;
            inValue.Body.sqlSource = sqlSource;
            WebServiceAPI.setCRVToIMGResponse retVal = ((WebServiceAPI.WebServiceAPISoap)(this)).setCRVToIMG(inValue);
            return retVal.Body.setCRVToIMGResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceAPI.setCRVToIMGResponse> WebServiceAPI.WebServiceAPISoap.setCRVToIMGAsync(WebServiceAPI.setCRVToIMGRequest request)
        {
            return base.Channel.setCRVToIMGAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceAPI.setCRVToIMGResponse> setCRVToIMGAsync(string strCRVName, string strScrpit, string strPdfFileName, string strImgFileName, string sqlUserID, string sqlPassword, string sqlCatalog, string sqlSource)
        {
            WebServiceAPI.setCRVToIMGRequest inValue = new WebServiceAPI.setCRVToIMGRequest();
            inValue.Body = new WebServiceAPI.setCRVToIMGRequestBody();
            inValue.Body.strCRVName = strCRVName;
            inValue.Body.strScrpit = strScrpit;
            inValue.Body.strPdfFileName = strPdfFileName;
            inValue.Body.strImgFileName = strImgFileName;
            inValue.Body.sqlUserID = sqlUserID;
            inValue.Body.sqlPassword = sqlPassword;
            inValue.Body.sqlCatalog = sqlCatalog;
            inValue.Body.sqlSource = sqlSource;
            return ((WebServiceAPI.WebServiceAPISoap)(this)).setCRVToIMGAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceAPISoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceAPISoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceAPISoap))
            {
                return new System.ServiceModel.EndpointAddress("http://172.23.238.179/WebAPI/WebServiceAPI.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceAPISoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://172.23.238.179/WebAPI/WebServiceAPI.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebServiceAPISoap,
            
            WebServiceAPISoap12,
        }
    }
}
