//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS1209_PrExcel
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FS1209_PrExcel.FS1209Soap")]
    public interface FS1209Soap
    {
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 dtContent 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintExcel_1209_1", ReplyAction="*")]
        FS1209_PrExcel.PrintExcel_1209_1Response PrintExcel_1209_1(FS1209_PrExcel.PrintExcel_1209_1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintExcel_1209_1", ReplyAction="*")]
        System.Threading.Tasks.Task<FS1209_PrExcel.PrintExcel_1209_1Response> PrintExcel_1209_1Async(FS1209_PrExcel.PrintExcel_1209_1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintExcel_1209_1Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintExcel_1209_1", Namespace="http://tempuri.org/", Order=0)]
        public FS1209_PrExcel.PrintExcel_1209_1RequestBody Body;
        
        public PrintExcel_1209_1Request()
        {
        }
        
        public PrintExcel_1209_1Request(FS1209_PrExcel.PrintExcel_1209_1RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintExcel_1209_1RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dtContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dtExcel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strTemplateFileFullName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string vcorderno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string vcPorType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string printIme;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string printDay;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string vcComDate01;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string vcBanZhi01;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string strPrinterName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string pagetotal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string pageno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string hejrange;
        
        public PrintExcel_1209_1RequestBody()
        {
        }
        
        public PrintExcel_1209_1RequestBody(string dtContent, string dtExcel, string strTemplateFileFullName, string vcorderno, string vcPorType, string User, string printIme, string printDay, string vcComDate01, string vcBanZhi01, string strPrinterName, string pagetotal, string pageno, string hejrange)
        {
            this.dtContent = dtContent;
            this.dtExcel = dtExcel;
            this.strTemplateFileFullName = strTemplateFileFullName;
            this.vcorderno = vcorderno;
            this.vcPorType = vcPorType;
            this.User = User;
            this.printIme = printIme;
            this.printDay = printDay;
            this.vcComDate01 = vcComDate01;
            this.vcBanZhi01 = vcBanZhi01;
            this.strPrinterName = strPrinterName;
            this.pagetotal = pagetotal;
            this.pageno = pageno;
            this.hejrange = hejrange;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintExcel_1209_1Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintExcel_1209_1Response", Namespace="http://tempuri.org/", Order=0)]
        public FS1209_PrExcel.PrintExcel_1209_1ResponseBody Body;
        
        public PrintExcel_1209_1Response()
        {
        }
        
        public PrintExcel_1209_1Response(FS1209_PrExcel.PrintExcel_1209_1ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintExcel_1209_1ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrintExcel_1209_1Result;
        
        public PrintExcel_1209_1ResponseBody()
        {
        }
        
        public PrintExcel_1209_1ResponseBody(string PrintExcel_1209_1Result)
        {
            this.PrintExcel_1209_1Result = PrintExcel_1209_1Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface FS1209SoapChannel : FS1209_PrExcel.FS1209Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class FS1209SoapClient : System.ServiceModel.ClientBase<FS1209_PrExcel.FS1209Soap>, FS1209_PrExcel.FS1209Soap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FS1209SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(FS1209SoapClient.GetBindingForEndpoint(endpointConfiguration), FS1209SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FS1209SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FS1209SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FS1209SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FS1209SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FS1209SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FS1209_PrExcel.PrintExcel_1209_1Response FS1209_PrExcel.FS1209Soap.PrintExcel_1209_1(FS1209_PrExcel.PrintExcel_1209_1Request request)
        {
            return base.Channel.PrintExcel_1209_1(request);
        }
        
        public string PrintExcel_1209_1(string dtContent, string dtExcel, string strTemplateFileFullName, string vcorderno, string vcPorType, string User, string printIme, string printDay, string vcComDate01, string vcBanZhi01, string strPrinterName, string pagetotal, string pageno, string hejrange)
        {
            FS1209_PrExcel.PrintExcel_1209_1Request inValue = new FS1209_PrExcel.PrintExcel_1209_1Request();
            inValue.Body = new FS1209_PrExcel.PrintExcel_1209_1RequestBody();
            inValue.Body.dtContent = dtContent;
            inValue.Body.dtExcel = dtExcel;
            inValue.Body.strTemplateFileFullName = strTemplateFileFullName;
            inValue.Body.vcorderno = vcorderno;
            inValue.Body.vcPorType = vcPorType;
            inValue.Body.User = User;
            inValue.Body.printIme = printIme;
            inValue.Body.printDay = printDay;
            inValue.Body.vcComDate01 = vcComDate01;
            inValue.Body.vcBanZhi01 = vcBanZhi01;
            inValue.Body.strPrinterName = strPrinterName;
            inValue.Body.pagetotal = pagetotal;
            inValue.Body.pageno = pageno;
            inValue.Body.hejrange = hejrange;
            FS1209_PrExcel.PrintExcel_1209_1Response retVal = ((FS1209_PrExcel.FS1209Soap)(this)).PrintExcel_1209_1(inValue);
            return retVal.Body.PrintExcel_1209_1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FS1209_PrExcel.PrintExcel_1209_1Response> FS1209_PrExcel.FS1209Soap.PrintExcel_1209_1Async(FS1209_PrExcel.PrintExcel_1209_1Request request)
        {
            return base.Channel.PrintExcel_1209_1Async(request);
        }
        
        public System.Threading.Tasks.Task<FS1209_PrExcel.PrintExcel_1209_1Response> PrintExcel_1209_1Async(string dtContent, string dtExcel, string strTemplateFileFullName, string vcorderno, string vcPorType, string User, string printIme, string printDay, string vcComDate01, string vcBanZhi01, string strPrinterName, string pagetotal, string pageno, string hejrange)
        {
            FS1209_PrExcel.PrintExcel_1209_1Request inValue = new FS1209_PrExcel.PrintExcel_1209_1Request();
            inValue.Body = new FS1209_PrExcel.PrintExcel_1209_1RequestBody();
            inValue.Body.dtContent = dtContent;
            inValue.Body.dtExcel = dtExcel;
            inValue.Body.strTemplateFileFullName = strTemplateFileFullName;
            inValue.Body.vcorderno = vcorderno;
            inValue.Body.vcPorType = vcPorType;
            inValue.Body.User = User;
            inValue.Body.printIme = printIme;
            inValue.Body.printDay = printDay;
            inValue.Body.vcComDate01 = vcComDate01;
            inValue.Body.vcBanZhi01 = vcBanZhi01;
            inValue.Body.strPrinterName = strPrinterName;
            inValue.Body.pagetotal = pagetotal;
            inValue.Body.pageno = pageno;
            inValue.Body.hejrange = hejrange;
            return ((FS1209_PrExcel.FS1209Soap)(this)).PrintExcel_1209_1Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FS1209Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.FS1209Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FS1209Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8089/FS1209.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.FS1209Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8089/FS1209.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            FS1209Soap,
            
            FS1209Soap12,
        }
    }
}
