//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintCR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrintCR.PrintTableSoap")]
    public interface PrintTableSoap
    {
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 vcTableName 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintCR", ReplyAction="*")]
        PrintCR.PrintCRResponse PrintCR(PrintCR.PrintCRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintCR", ReplyAction="*")]
        System.Threading.Tasks.Task<PrintCR.PrintCRResponse> PrintCRAsync(PrintCR.PrintCRRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 dtContent 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintExcel_Confirmation", ReplyAction="*")]
        PrintCR.PrintExcel_ConfirmationResponse PrintExcel_Confirmation(PrintCR.PrintExcel_ConfirmationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintExcel_Confirmation", ReplyAction="*")]
        System.Threading.Tasks.Task<PrintCR.PrintExcel_ConfirmationResponse> PrintExcel_ConfirmationAsync(PrintCR.PrintExcel_ConfirmationRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 dtContent 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintExcel_Confirmation_PrintDate", ReplyAction="*")]
        PrintCR.PrintExcel_Confirmation_PrintDateResponse PrintExcel_Confirmation_PrintDate(PrintCR.PrintExcel_Confirmation_PrintDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintExcel_Confirmation_PrintDate", ReplyAction="*")]
        System.Threading.Tasks.Task<PrintCR.PrintExcel_Confirmation_PrintDateResponse> PrintExcel_Confirmation_PrintDateAsync(PrintCR.PrintExcel_Confirmation_PrintDateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintCRRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintCR", Namespace="http://tempuri.org/", Order=0)]
        public PrintCR.PrintCRRequestBody Body;
        
        public PrintCRRequest()
        {
        }
        
        public PrintCRRequest(PrintCR.PrintCRRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintCRRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vcTableName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string vcFieldName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string vcPrinterName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string vcCRTemplateName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string vcDBServerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string vcDBName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string vcDBUserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string vcDBPassword;
        
        public PrintCRRequestBody()
        {
        }
        
        public PrintCRRequestBody(string vcTableName, string vcFieldName, string vcPrinterName, string vcCRTemplateName, string vcDBServerName, string vcDBName, string vcDBUserId, string vcDBPassword)
        {
            this.vcTableName = vcTableName;
            this.vcFieldName = vcFieldName;
            this.vcPrinterName = vcPrinterName;
            this.vcCRTemplateName = vcCRTemplateName;
            this.vcDBServerName = vcDBServerName;
            this.vcDBName = vcDBName;
            this.vcDBUserId = vcDBUserId;
            this.vcDBPassword = vcDBPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintCRResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintCRResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrintCR.PrintCRResponseBody Body;
        
        public PrintCRResponse()
        {
        }
        
        public PrintCRResponse(PrintCR.PrintCRResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintCRResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrintCRResult;
        
        public PrintCRResponseBody()
        {
        }
        
        public PrintCRResponseBody(string PrintCRResult)
        {
            this.PrintCRResult = PrintCRResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintExcel_ConfirmationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintExcel_Confirmation", Namespace="http://tempuri.org/", Order=0)]
        public PrintCR.PrintExcel_ConfirmationRequestBody Body;
        
        public PrintExcel_ConfirmationRequest()
        {
        }
        
        public PrintExcel_ConfirmationRequest(PrintCR.PrintExcel_ConfirmationRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintExcel_ConfirmationRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dtContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dtExcel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strTemplateFileFullName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string vcorderno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string vcPorType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string printIme;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string printDay;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string vcComDate01;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string vcBanZhi01;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string strPrinterName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string pagetotal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string pageno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string hejrange;
        
        public PrintExcel_ConfirmationRequestBody()
        {
        }
        
        public PrintExcel_ConfirmationRequestBody(string dtContent, string dtExcel, string strTemplateFileFullName, string vcorderno, string vcPorType, string User, string printIme, string printDay, string vcComDate01, string vcBanZhi01, string strPrinterName, string pagetotal, string pageno, string hejrange)
        {
            this.dtContent = dtContent;
            this.dtExcel = dtExcel;
            this.strTemplateFileFullName = strTemplateFileFullName;
            this.vcorderno = vcorderno;
            this.vcPorType = vcPorType;
            this.User = User;
            this.printIme = printIme;
            this.printDay = printDay;
            this.vcComDate01 = vcComDate01;
            this.vcBanZhi01 = vcBanZhi01;
            this.strPrinterName = strPrinterName;
            this.pagetotal = pagetotal;
            this.pageno = pageno;
            this.hejrange = hejrange;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintExcel_ConfirmationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintExcel_ConfirmationResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrintCR.PrintExcel_ConfirmationResponseBody Body;
        
        public PrintExcel_ConfirmationResponse()
        {
        }
        
        public PrintExcel_ConfirmationResponse(PrintCR.PrintExcel_ConfirmationResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintExcel_ConfirmationResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrintExcel_ConfirmationResult;
        
        public PrintExcel_ConfirmationResponseBody()
        {
        }
        
        public PrintExcel_ConfirmationResponseBody(string PrintExcel_ConfirmationResult)
        {
            this.PrintExcel_ConfirmationResult = PrintExcel_ConfirmationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintExcel_Confirmation_PrintDateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintExcel_Confirmation_PrintDate", Namespace="http://tempuri.org/", Order=0)]
        public PrintCR.PrintExcel_Confirmation_PrintDateRequestBody Body;
        
        public PrintExcel_Confirmation_PrintDateRequest()
        {
        }
        
        public PrintExcel_Confirmation_PrintDateRequest(PrintCR.PrintExcel_Confirmation_PrintDateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintExcel_Confirmation_PrintDateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dtContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dtExcel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strTemplateFileFullName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string vcorderno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string vcPorType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string User;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string printIme;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string printDay;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string vcComDate01;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string vcBanZhi01;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string strPrinterName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string pagetotal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string pageno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string hejrange;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string vcPrintDate;
        
        public PrintExcel_Confirmation_PrintDateRequestBody()
        {
        }
        
        public PrintExcel_Confirmation_PrintDateRequestBody(string dtContent, string dtExcel, string strTemplateFileFullName, string vcorderno, string vcPorType, string User, string printIme, string printDay, string vcComDate01, string vcBanZhi01, string strPrinterName, string pagetotal, string pageno, string hejrange, string vcPrintDate)
        {
            this.dtContent = dtContent;
            this.dtExcel = dtExcel;
            this.strTemplateFileFullName = strTemplateFileFullName;
            this.vcorderno = vcorderno;
            this.vcPorType = vcPorType;
            this.User = User;
            this.printIme = printIme;
            this.printDay = printDay;
            this.vcComDate01 = vcComDate01;
            this.vcBanZhi01 = vcBanZhi01;
            this.strPrinterName = strPrinterName;
            this.pagetotal = pagetotal;
            this.pageno = pageno;
            this.hejrange = hejrange;
            this.vcPrintDate = vcPrintDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintExcel_Confirmation_PrintDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintExcel_Confirmation_PrintDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrintCR.PrintExcel_Confirmation_PrintDateResponseBody Body;
        
        public PrintExcel_Confirmation_PrintDateResponse()
        {
        }
        
        public PrintExcel_Confirmation_PrintDateResponse(PrintCR.PrintExcel_Confirmation_PrintDateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintExcel_Confirmation_PrintDateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrintExcel_Confirmation_PrintDateResult;
        
        public PrintExcel_Confirmation_PrintDateResponseBody()
        {
        }
        
        public PrintExcel_Confirmation_PrintDateResponseBody(string PrintExcel_Confirmation_PrintDateResult)
        {
            this.PrintExcel_Confirmation_PrintDateResult = PrintExcel_Confirmation_PrintDateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface PrintTableSoapChannel : PrintCR.PrintTableSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PrintTableSoapClient : System.ServiceModel.ClientBase<PrintCR.PrintTableSoap>, PrintCR.PrintTableSoap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PrintTableSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PrintTableSoapClient.GetBindingForEndpoint(endpointConfiguration), PrintTableSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PrintTableSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PrintTableSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PrintTableSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PrintTableSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PrintTableSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrintCR.PrintCRResponse PrintCR.PrintTableSoap.PrintCR(PrintCR.PrintCRRequest request)
        {
            return base.Channel.PrintCR(request);
        }
        
        public string PrintCR(string vcTableName, string vcFieldName, string vcPrinterName, string vcCRTemplateName, string vcDBServerName, string vcDBName, string vcDBUserId, string vcDBPassword)
        {
            PrintCR.PrintCRRequest inValue = new PrintCR.PrintCRRequest();
            inValue.Body = new PrintCR.PrintCRRequestBody();
            inValue.Body.vcTableName = vcTableName;
            inValue.Body.vcFieldName = vcFieldName;
            inValue.Body.vcPrinterName = vcPrinterName;
            inValue.Body.vcCRTemplateName = vcCRTemplateName;
            inValue.Body.vcDBServerName = vcDBServerName;
            inValue.Body.vcDBName = vcDBName;
            inValue.Body.vcDBUserId = vcDBUserId;
            inValue.Body.vcDBPassword = vcDBPassword;
            PrintCR.PrintCRResponse retVal = ((PrintCR.PrintTableSoap)(this)).PrintCR(inValue);
            return retVal.Body.PrintCRResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrintCR.PrintCRResponse> PrintCR.PrintTableSoap.PrintCRAsync(PrintCR.PrintCRRequest request)
        {
            return base.Channel.PrintCRAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrintCR.PrintCRResponse> PrintCRAsync(string vcTableName, string vcFieldName, string vcPrinterName, string vcCRTemplateName, string vcDBServerName, string vcDBName, string vcDBUserId, string vcDBPassword)
        {
            PrintCR.PrintCRRequest inValue = new PrintCR.PrintCRRequest();
            inValue.Body = new PrintCR.PrintCRRequestBody();
            inValue.Body.vcTableName = vcTableName;
            inValue.Body.vcFieldName = vcFieldName;
            inValue.Body.vcPrinterName = vcPrinterName;
            inValue.Body.vcCRTemplateName = vcCRTemplateName;
            inValue.Body.vcDBServerName = vcDBServerName;
            inValue.Body.vcDBName = vcDBName;
            inValue.Body.vcDBUserId = vcDBUserId;
            inValue.Body.vcDBPassword = vcDBPassword;
            return ((PrintCR.PrintTableSoap)(this)).PrintCRAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrintCR.PrintExcel_ConfirmationResponse PrintCR.PrintTableSoap.PrintExcel_Confirmation(PrintCR.PrintExcel_ConfirmationRequest request)
        {
            return base.Channel.PrintExcel_Confirmation(request);
        }
        
        public string PrintExcel_Confirmation(string dtContent, string dtExcel, string strTemplateFileFullName, string vcorderno, string vcPorType, string User, string printIme, string printDay, string vcComDate01, string vcBanZhi01, string strPrinterName, string pagetotal, string pageno, string hejrange)
        {
            PrintCR.PrintExcel_ConfirmationRequest inValue = new PrintCR.PrintExcel_ConfirmationRequest();
            inValue.Body = new PrintCR.PrintExcel_ConfirmationRequestBody();
            inValue.Body.dtContent = dtContent;
            inValue.Body.dtExcel = dtExcel;
            inValue.Body.strTemplateFileFullName = strTemplateFileFullName;
            inValue.Body.vcorderno = vcorderno;
            inValue.Body.vcPorType = vcPorType;
            inValue.Body.User = User;
            inValue.Body.printIme = printIme;
            inValue.Body.printDay = printDay;
            inValue.Body.vcComDate01 = vcComDate01;
            inValue.Body.vcBanZhi01 = vcBanZhi01;
            inValue.Body.strPrinterName = strPrinterName;
            inValue.Body.pagetotal = pagetotal;
            inValue.Body.pageno = pageno;
            inValue.Body.hejrange = hejrange;
            PrintCR.PrintExcel_ConfirmationResponse retVal = ((PrintCR.PrintTableSoap)(this)).PrintExcel_Confirmation(inValue);
            return retVal.Body.PrintExcel_ConfirmationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrintCR.PrintExcel_ConfirmationResponse> PrintCR.PrintTableSoap.PrintExcel_ConfirmationAsync(PrintCR.PrintExcel_ConfirmationRequest request)
        {
            return base.Channel.PrintExcel_ConfirmationAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrintCR.PrintExcel_ConfirmationResponse> PrintExcel_ConfirmationAsync(string dtContent, string dtExcel, string strTemplateFileFullName, string vcorderno, string vcPorType, string User, string printIme, string printDay, string vcComDate01, string vcBanZhi01, string strPrinterName, string pagetotal, string pageno, string hejrange)
        {
            PrintCR.PrintExcel_ConfirmationRequest inValue = new PrintCR.PrintExcel_ConfirmationRequest();
            inValue.Body = new PrintCR.PrintExcel_ConfirmationRequestBody();
            inValue.Body.dtContent = dtContent;
            inValue.Body.dtExcel = dtExcel;
            inValue.Body.strTemplateFileFullName = strTemplateFileFullName;
            inValue.Body.vcorderno = vcorderno;
            inValue.Body.vcPorType = vcPorType;
            inValue.Body.User = User;
            inValue.Body.printIme = printIme;
            inValue.Body.printDay = printDay;
            inValue.Body.vcComDate01 = vcComDate01;
            inValue.Body.vcBanZhi01 = vcBanZhi01;
            inValue.Body.strPrinterName = strPrinterName;
            inValue.Body.pagetotal = pagetotal;
            inValue.Body.pageno = pageno;
            inValue.Body.hejrange = hejrange;
            return ((PrintCR.PrintTableSoap)(this)).PrintExcel_ConfirmationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrintCR.PrintExcel_Confirmation_PrintDateResponse PrintCR.PrintTableSoap.PrintExcel_Confirmation_PrintDate(PrintCR.PrintExcel_Confirmation_PrintDateRequest request)
        {
            return base.Channel.PrintExcel_Confirmation_PrintDate(request);
        }
        
        public string PrintExcel_Confirmation_PrintDate(string dtContent, string dtExcel, string strTemplateFileFullName, string vcorderno, string vcPorType, string User, string printIme, string printDay, string vcComDate01, string vcBanZhi01, string strPrinterName, string pagetotal, string pageno, string hejrange, string vcPrintDate)
        {
            PrintCR.PrintExcel_Confirmation_PrintDateRequest inValue = new PrintCR.PrintExcel_Confirmation_PrintDateRequest();
            inValue.Body = new PrintCR.PrintExcel_Confirmation_PrintDateRequestBody();
            inValue.Body.dtContent = dtContent;
            inValue.Body.dtExcel = dtExcel;
            inValue.Body.strTemplateFileFullName = strTemplateFileFullName;
            inValue.Body.vcorderno = vcorderno;
            inValue.Body.vcPorType = vcPorType;
            inValue.Body.User = User;
            inValue.Body.printIme = printIme;
            inValue.Body.printDay = printDay;
            inValue.Body.vcComDate01 = vcComDate01;
            inValue.Body.vcBanZhi01 = vcBanZhi01;
            inValue.Body.strPrinterName = strPrinterName;
            inValue.Body.pagetotal = pagetotal;
            inValue.Body.pageno = pageno;
            inValue.Body.hejrange = hejrange;
            inValue.Body.vcPrintDate = vcPrintDate;
            PrintCR.PrintExcel_Confirmation_PrintDateResponse retVal = ((PrintCR.PrintTableSoap)(this)).PrintExcel_Confirmation_PrintDate(inValue);
            return retVal.Body.PrintExcel_Confirmation_PrintDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrintCR.PrintExcel_Confirmation_PrintDateResponse> PrintCR.PrintTableSoap.PrintExcel_Confirmation_PrintDateAsync(PrintCR.PrintExcel_Confirmation_PrintDateRequest request)
        {
            return base.Channel.PrintExcel_Confirmation_PrintDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrintCR.PrintExcel_Confirmation_PrintDateResponse> PrintExcel_Confirmation_PrintDateAsync(string dtContent, string dtExcel, string strTemplateFileFullName, string vcorderno, string vcPorType, string User, string printIme, string printDay, string vcComDate01, string vcBanZhi01, string strPrinterName, string pagetotal, string pageno, string hejrange, string vcPrintDate)
        {
            PrintCR.PrintExcel_Confirmation_PrintDateRequest inValue = new PrintCR.PrintExcel_Confirmation_PrintDateRequest();
            inValue.Body = new PrintCR.PrintExcel_Confirmation_PrintDateRequestBody();
            inValue.Body.dtContent = dtContent;
            inValue.Body.dtExcel = dtExcel;
            inValue.Body.strTemplateFileFullName = strTemplateFileFullName;
            inValue.Body.vcorderno = vcorderno;
            inValue.Body.vcPorType = vcPorType;
            inValue.Body.User = User;
            inValue.Body.printIme = printIme;
            inValue.Body.printDay = printDay;
            inValue.Body.vcComDate01 = vcComDate01;
            inValue.Body.vcBanZhi01 = vcBanZhi01;
            inValue.Body.strPrinterName = strPrinterName;
            inValue.Body.pagetotal = pagetotal;
            inValue.Body.pageno = pageno;
            inValue.Body.hejrange = hejrange;
            inValue.Body.vcPrintDate = vcPrintDate;
            return ((PrintCR.PrintTableSoap)(this)).PrintExcel_Confirmation_PrintDateAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PrintTableSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PrintTableSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PrintTableSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:25011/PrintTable.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PrintTableSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:25011/PrintTable.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PrintTableSoap,
            
            PrintTableSoap12,
        }
    }
}
