//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintCR
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrintCR.PrintTableSoap")]
    public interface PrintTableSoap
    {
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 vcTableName 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintCR", ReplyAction="*")]
        PrintCR.PrintCRResponse PrintCR(PrintCR.PrintCRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintCR", ReplyAction="*")]
        System.Threading.Tasks.Task<PrintCR.PrintCRResponse> PrintCRAsync(PrintCR.PrintCRRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintCRRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintCR", Namespace="http://tempuri.org/", Order=0)]
        public PrintCR.PrintCRRequestBody Body;
        
        public PrintCRRequest()
        {
        }
        
        public PrintCRRequest(PrintCR.PrintCRRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintCRRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string vcTableName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string vcFieldName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string vcPrinterName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string vcCRTemplateName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string vcDBServerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string vcDBName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string vcDBUserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string vcDBPassword;
        
        public PrintCRRequestBody()
        {
        }
        
        public PrintCRRequestBody(string vcTableName, string vcFieldName, string vcPrinterName, string vcCRTemplateName, string vcDBServerName, string vcDBName, string vcDBUserId, string vcDBPassword)
        {
            this.vcTableName = vcTableName;
            this.vcFieldName = vcFieldName;
            this.vcPrinterName = vcPrinterName;
            this.vcCRTemplateName = vcCRTemplateName;
            this.vcDBServerName = vcDBServerName;
            this.vcDBName = vcDBName;
            this.vcDBUserId = vcDBUserId;
            this.vcDBPassword = vcDBPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrintCRResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintCRResponse", Namespace="http://tempuri.org/", Order=0)]
        public PrintCR.PrintCRResponseBody Body;
        
        public PrintCRResponse()
        {
        }
        
        public PrintCRResponse(PrintCR.PrintCRResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PrintCRResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrintCRResult;
        
        public PrintCRResponseBody()
        {
        }
        
        public PrintCRResponseBody(string PrintCRResult)
        {
            this.PrintCRResult = PrintCRResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface PrintTableSoapChannel : PrintCR.PrintTableSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PrintTableSoapClient : System.ServiceModel.ClientBase<PrintCR.PrintTableSoap>, PrintCR.PrintTableSoap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PrintTableSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PrintTableSoapClient.GetBindingForEndpoint(endpointConfiguration), PrintTableSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PrintTableSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PrintTableSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PrintTableSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PrintTableSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PrintTableSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrintCR.PrintCRResponse PrintCR.PrintTableSoap.PrintCR(PrintCR.PrintCRRequest request)
        {
            return base.Channel.PrintCR(request);
        }
        
        public string PrintCR(string vcTableName, string vcFieldName, string vcPrinterName, string vcCRTemplateName, string vcDBServerName, string vcDBName, string vcDBUserId, string vcDBPassword)
        {
            PrintCR.PrintCRRequest inValue = new PrintCR.PrintCRRequest();
            inValue.Body = new PrintCR.PrintCRRequestBody();
            inValue.Body.vcTableName = vcTableName;
            inValue.Body.vcFieldName = vcFieldName;
            inValue.Body.vcPrinterName = vcPrinterName;
            inValue.Body.vcCRTemplateName = vcCRTemplateName;
            inValue.Body.vcDBServerName = vcDBServerName;
            inValue.Body.vcDBName = vcDBName;
            inValue.Body.vcDBUserId = vcDBUserId;
            inValue.Body.vcDBPassword = vcDBPassword;
            PrintCR.PrintCRResponse retVal = ((PrintCR.PrintTableSoap)(this)).PrintCR(inValue);
            return retVal.Body.PrintCRResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrintCR.PrintCRResponse> PrintCR.PrintTableSoap.PrintCRAsync(PrintCR.PrintCRRequest request)
        {
            return base.Channel.PrintCRAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrintCR.PrintCRResponse> PrintCRAsync(string vcTableName, string vcFieldName, string vcPrinterName, string vcCRTemplateName, string vcDBServerName, string vcDBName, string vcDBUserId, string vcDBPassword)
        {
            PrintCR.PrintCRRequest inValue = new PrintCR.PrintCRRequest();
            inValue.Body = new PrintCR.PrintCRRequestBody();
            inValue.Body.vcTableName = vcTableName;
            inValue.Body.vcFieldName = vcFieldName;
            inValue.Body.vcPrinterName = vcPrinterName;
            inValue.Body.vcCRTemplateName = vcCRTemplateName;
            inValue.Body.vcDBServerName = vcDBServerName;
            inValue.Body.vcDBName = vcDBName;
            inValue.Body.vcDBUserId = vcDBUserId;
            inValue.Body.vcDBPassword = vcDBPassword;
            return ((PrintCR.PrintTableSoap)(this)).PrintCRAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PrintTableSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PrintTableSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PrintTableSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:63480/PrintTable.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PrintTableSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:63480/PrintTable.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PrintTableSoap,
            
            PrintTableSoap12,
        }
    }
}
